config/routes.rb
Rails.application.routes.draw do

  # Kullanıcı kaydı ve girişi için özel rotalar
  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:new, :create]
  post '/register', to: 'users#create', as: :register
  post '/login', to: 'sessions#create', as: :login
  post '/logout', to: 'sessions#destroy', as: :logout

  resources :books, only: [:index, :show, :create, :update, :destroy]

  resource :cart, only: [:show] do
    post 'checkout', on: :member
    delete 'clear', on: :member
    resources :cart_items, only: [:create, :update, :destroy]
  end

  # Sağlık durumu kontrolü için rota
  get '/up', to: 'rails/health#show', as: :rails_health_check

  # Ödeme için rotalar
  post '/payments/process_payment', to: 'payments#process_payment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :cart_items
    has_many :carts, through: :cart_items
  
    validates :title, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 0 }
    validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  end
  

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :books, through: :cart_items

  # Kitap ekler veya var olan kitabın miktarını günceller
  def add_book(book, quantity)
    current_item = cart_items.find_by(book_id: book.id)
    if current_item
      current_item.quantity += quantity
      current_item.save
    else
      current_item = cart_items.create(book_id: book.id, quantity: quantity)
    end
    current_item
  end

  # Toplam sepet tutarını hesaplayan metod
  def total_amount
    cart_items.joins(:book).sum('books.price * cart_items.quantity')
  end

  def checkout
    clear_cart_items
    true
  end

  def clear_cart_items
    cart_items.destroy_all
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :book

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_default_cart
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }

  has_one :cart, dependent: :destroy
  private

  def create_default_cart
    Cart.create(user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  before_action :authorize_request
  attr_reader :current_user

  private


  def authorize_request
    header = request.headers['Authorization']
    header = header.split(' ').last if header
    begin
      @decoded = decode_jwt(header)
      @current_user = User.find(@decoded[:user_id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: "Access denied" }, status: :unauthorized
    rescue JWT::DecodeError => e
      render json: { errors: "Access denied" }, status: :unauthorized
    end
  end
  def decode_jwt(token)
    body = JWT.decode(token, Rails.application.secret_key_base, true, algorithm: 'HS256')[0]
    HashWithIndifferentAccess.new body
  rescue JWT::ExpiredSignature, JWT::VerificationError => e
    raise JWT::DecodeError, e.message
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :update, :destroy]
  
    # Tüm kitapların listelenmesi
    def index
      @books = Book.all
      render json: @books
    end
  
    # Belirli bir kitabın detaylarının gösterilmesi
    def show
      render json: @book
    end
  
    # Yeni bir kitabın eklenmesi
    def create
      @book = Book.new(book_params)
  
      if @book.save
        render json: @book, status: :created
      else
        render json: @book.errors, status: :unprocessable_entity
      end
    end
  
    # Mevcut bir kitabın güncellenmesi
    def update
      if @book.update(book_params)
        render json: @book
      else
        render json: @book.errors, status: :unprocessable_entity
      end
    end
  
    # Mevcut bir kitabın silinmesi
    def destroy
      @book.destroy
    end
  
    private
  
    # İlgili kitabı bulmak için kullanılan yardımcı metod
    def set_book
      @book = Book.find(params[:id])
    end
  
    # Kitap oluşturma/güncelleme işlemleri için izin verilen parametreler
    def book_params
      params.require(:book).permit(:title, :description, :price, :stock)
    end
  end
  

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    before_action :authorize_request
    before_action :set_cart
    before_action :set_cart_item, only: [:update, :destroy]
  
    # Sepete yeni bir kitap ekleme
    def create
      book = Book.find(params[:book_id])
      quantity = params[:quantity].to_i
  
      if @cart.add_book(book, quantity)
        render json: { message: 'Kitap sepete eklendi.', cart: @cart }, status: :created
      else
        render json: { message: 'Kitap eklenemedi.' }, status: :unprocessable_entity
      end
    end
  
    # Sepet öğesinin miktarını güncelleme
    def update
      quantity = params[:quantity].to_i
  
      if quantity > 0
        @cart_item.update(quantity: quantity)
        render json: { message: 'Sepet güncellendi.', cart: @cart }, status: :ok
      else
        @cart_item.destroy
        render json: { message: 'Kitap sepetten çıkarıldı.', cart: @cart }, status: :ok
      end
    end
  
    # Sepetten belirli bir kitabı çıkarma
    def destroy
      @cart_item.destroy
      render json: { message: 'Kitap sepetten çıkarıldı.', cart: @cart }, status: :ok
    end
  
    private
  
    # Kullanıcının sepetini ayarlayan yardımcı metod
    def set_cart
      @cart = current_user.cart || current_user.create_cart
    end
  
    # İlgili sepet öğesini ayarlayan yardımcı metod
    def set_cart_item
      @cart_item = @cart.cart_items.find(params[:id])
    end
  end
  

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authorize_request
  before_action :set_cart, only: [:show, :checkout, :clear]

  # Sepetin detaylarının görüntülenmesi
  def show
    render json: @cart.as_json(include: { cart_items: { include: :book } })
  end

  # Ödeme işleminin gerçekleştirilmesi
  def checkout
    if @cart.cart_items.any?
      total_amount = @cart.total_amount  #
      if process_payment(total_amount)  
        @cart.clear_cart_items  
        render json: {
          message: "Ödeme başarılı. Siparişiniz alındı. Toplam ödediğiniz tutar: #{total_amount} TL"}, status: :ok
      else
        render json: {
          message: 'Ödeme işlemi başarısız. Lütfen tekrar deneyiniz.'
        }, status: :unprocessable_entity
      end
    else
      render json: { message: 'Sepetiniz boş.' }, status: :unprocessable_entity
    end
  end

  
  def clear
    @cart.clear
    render json: { message: 'Sepet temizlendi.' }, status: :ok
  end
  private


  # Ödeme işlemini simüle eden metod
  def process_payment(amount)

    true
  end

  # Kullanıcının sepetini ayarlayan yardımcı metod
  def set_cart
    @cart = current_user.cart || current_user.create_cart
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ActionController::Cookies
  skip_before_action :authorize_request, only: :create  

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      token = generate_jwt(user)
      cookies.signed[:jwt] = { value: token, httponly: true, expires: 24.hours.from_now }  
      render json: { jwt: token }
    else
      render json: { error: 'Invalid username or password' }, status: :unauthorized
    end
  end

  def destroy
    cookies.delete(:jwt)      
    render json: { message: 'Logged out successfully' }, status: :ok
  end

  private


  def generate_jwt(user)
    JWT.encode({ user_id: user.id, exp: 24.hours.from_now.to_i }, Rails.application.secret_key_base, 'HS256')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize_request, only: [:create, :new]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: { message: 'User was successfully created.' }, status: :created
    else
      render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher, id: :book_publisher %>
  </div>

  <div class

app/views/books/edit.html.erb
<!-- app/views/cart_items/edit.html.erb -->

<h1>Edit Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Publisher</th>
    <th>Price</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.publisher %></td>
      <td><%= number_to_currency(book.price) %></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Book' %>
  </div>
<% end %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>
<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>
<p>
  <strong>Price:</strong>
  <%= number_to_currency(@book.price) %>
</p>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item, local: true) do |form| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
        <% cart_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.label :book_id %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :subtotal %>
    <%= form.text_field :subtotal %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Edit Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<h1>Cart Items</h1>
<table>
  <thead>
    <tr>
      <th>Cart</th>
      <th>Book</th>
      <th>Quantity</th>
      <th>Subtotal</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.cart_id %></td>
        <td><%= cart_item.book_id %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= cart_item.subtotal %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart Item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p>
  <strong>Cart:</strong>
  <%= @cart_item.cart_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @cart_item.book_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart_item.quantity %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @cart_item.subtotal %>
</p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>

app/views/carts/index.html.erb
<!-- app/views/carts/index.html.erb -->

<h1>Carts</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Total Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user.email %></td>
        <td><%= number_to_currency(cart.total_price) %></td>
        <td><%= link_to 'Show', cart_path(cart) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/carts/show.html.erb
<!-- app/views/carts/show.html.erb -->

<h1>Cart for <%= @cart.user.email %></h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.book.title %></td>
        <td><%= cart_item.book.author %></td>
        <td><%= cart_item.book.publisher %></td>
        <td><%= number_to_currency(cart_item.book.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>Total Price: <%= number_to_currency(@cart.total_price) %></p>
<%= link_to 'Back to list', carts_path %>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->

<h1>Sign Up</h1>

<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit 'Sign Up' %>
  </div>
<% end %>